config/routes.rb
Rails.application.routes.draw do
  get "users" => "users#index"
  get "users/new" => "users#new"
  post "users" => "users#create"
  get "users/:id" => "users#show", as: :user
  get "users/:id/edit" => "users#edit", as: :edit_user
  patch "users/:id" => "users#update"
  delete 'users/:id' => 'users#destroy'

  get '/login'     => 'sessions#new'
  post '/login'    => 'sessions#create'
  delete '/logout' => 'sessions#destroy'

  get "games(.:format)" => "games#index"
  get "games/new" => "games#new"
  post "games" => "games#create"
  get "games/:id" => "games#show", as: :game
  get "games/:id/edit" => "games#edit", as: :edit_game
  patch "games/:id" => "games#update"
  delete "games/:id" => "games#destroy"

  resources :games do
    resources :gameusers
  end

  root :to => redirect('/games')

end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :users
  has_many :users, through: :gameusers
  has_many :gameusers
end

app/models/gameuser.rb
class Gameuser < ActiveRecord::Base
  belongs_to :game
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :alias, presence: true, length: { in: 6..20 }
  validates :email, presence: true, uniqueness: { case_sensitive: false }, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  # validates :gender, presence: true
  has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  has_many :gameusers
  has_many :games, through: :gameusers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper

  def authorized?
    redirect_to root_path unless current_user
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authorized?,  except: :index

  def index
    @games = Game.all
    respond_to do |format|
    format.html {
        render
    }
    format.json {
        render json: @games
    }
  end

  end

  def show
    @game = Game.find(params[:id])
  end

  def new
    @game = Game.new
  end

  def create
    # @game.user_id = current_user.id
    @game = Game.new(game_params)
    if @game.save
      # session[:id] = @user.id.to_s
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
    @game = Game.find(params[:id])
  end

  def update
      @game = Game.find(params[:id])

      if @game.update_attributes(game_params)
      redirect_to users_path
      else
        render :edit
      end
  end

  def destroy
    @game = Game.find(params[:id])
    @game.destroy
      respond_to do |format|
        format.html { redirect_to users_path, notice: 'Game was successfully destroyed.' }
        format.json { head :no_content }
    end
  end

  def AddUserToGame
    @game.users.push(current_user)
  end

  private

  def game_params
    params.require(:game).permit(:title, :court_name, :court_address, :sport, :game_at, :spots, :fee, :description, user_ids: [])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:login][:email])
    if user && user.authenticate(params[:login][:password])
      # make a new key in our session object called :user_id
      # which gets stored in a cookie in our browser
      session[:user_id] = user.id.to_s
      redirect_to games_path
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = "You have successfully logged out."
    redirect_to games_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorized?, except: [:new, :create] 

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:id] = @user.id.to_s
      redirect_to users_path
    else
      render :new
    end
  end

  def edit
		@user = User.find(params[:id])
	end

  def update
  		@user = User.find(params[:id])

  		if @user.update_attributes(user_params)
    	redirect_to users_path
  		else
  			render :edit
  		end
	end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
      respond_to do |format|
        format.html { redirect_to users_path, notice: 'User was successfully destroyed.' }
        format.json { head :no_content }
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :alias, :email, :phone, :gender, :height, :weight, :description, :password, :password_confirmation, :image, game_ids: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/games/edit.html.erb
<h1>Edit Your Game!</h1>
<%= form_for @game do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :court_name %>
    <%= f.text_field :court_name %>
  </div>
  <div>
    <%= f.label :court_address %>
    <%= f.text_field :court_address %>
  </div>
  <div>
    <%= f.label :sport %>
    <%= f.text_field :sport %>
  </div>
  <div>
    <%= f.label :game_at %>
    <%= f.text_field :game_at %>
  </div>
  <div>
    <%= f.label :spots %>
    <%= f.text_field :spots %>
  </div>
  <div>
    <%= f.label :fee %>
    <%= f.text_field :fee %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.submit "Save Changes!" %>
  </div>
<% end %>

app/views/games/index.html.erb
<h2>Find pickup games for your favorite sports!</h2>

<!-- Search Bar -->
<div class ="pull-right">
  <%= form_tag("/search", method: "get") do  %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
  <% end %>
</div>
<!-- Google Map Plugin -->
<div id="address-map" style="width: 100%; height: 450px;"></div>

<% @games.each do |game| %>
  <tr>
    <td><%= game.title %></td>
    <td><%= game.court_name %></td>
    <td><%= game.court_address %></td>
    <td><%= game.sport %></td>
    <td><%= game.game_at %></td>
    <td><%= game.spots %></td>
    <td><%= game.fee %></td>
    <td><%= game.description %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', game %></td>
    <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>

app/views/games/new.html.erb
<h1>Create a Game!</h1>
<%= form_for @game do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :court_name %>
    <%= f.text_field :court_name %>
  </div>
  <div>
    <%= f.label :court_address %>
    <%= f.text_field :court_address %>
  </div>
  <div>
    <%= f.label :sport %>
    <%= f.text_field :sport %>
  </div>
  <div>
    <%= f.label :game_at %>
    <%= f.text_field :game_at %>
  </div>
  <div>
    <%= f.label :spots %>
    <%= f.text_field :spots %>
  </div>
  <div>
    <%= f.label :fee %>
    <%= f.text_field :fee %>
  </div>
  <div>
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/games/show.html.erb
<strong>Title: </strong><%= @game.title %>
<br>
<br>
<strong>Venue: </strong><%= @game.court_name %>
<br>
<br>
<strong>Address: </strong><%= @game.court_address %>
<br>
<br>
<strong>Sport: </strong><%= @game.sport %>
<br>
<br>
<strong>Date & Time: </strong><%= @game.game_at %>
<br>
<br>
<strong>Spots: </strong><%= @game.spots %>
<br>
<br>
<strong>Fee: </strong><%= @game.fee %>
<br>
<br>
<strong>Description: </strong><%= @game.description %>
<br>
<br>
<%= link_to 'Join', edit_game_path, class:"btn btn-primary"  %>
<%= link_to 'Edit', edit_game_path, class:"btn btn-primary"  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PickupGameFinder</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Add the google maps library -->
  <script src="//maps.googleapis.com/maps/api/js?key=AIzaSyAs2qjvJgNP8iAu4-QS5md4S-OPSIwDXro"></script>
  <!-- Add JS from the asset pipeline afterwards -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</head>
<body>
  <div class = 'container'>

    <div class = 'page-header'>
      <ul class="nav nav-pills pull-right">
        <li><%= link_to 'Create Games', games_new_path %></li>
        <li><%= link_to 'My Games', games_new_path %></li>
        <li>
          <% if current_user %>
            <%= link_to 'My Profile', user_path(current_user.id) %>
          <% else %>
            <%= link_to 'Sign Up', users_new_path %>
          <% end %>
        </li>
        <li>
          <% if current_user %>
            <%= link_to 'Log Out', logout_path, method: :delete %>
          <% else %>
            <%= link_to 'Log In', login_path %>
          <% end %>
        </li>
      </ul>
        <h1>
          <%= link_to 'Streetball', root_path %>
          <small>Pickup Game Finder</small>
        </h1>
    </div>

    <div class = 'row'>
      <p class = "pull-right">
        <% if current_user %>
          Hello, <%= current_user.first_name %>
        <% end %>
      </p>
      <%= flash[:notice] %>
      <%= yield %>
    </div>

  </div>


</body>
</html>

app/views/users/edit.html.erb
<h1>Edit Your Profile</h1>
<form>
  <%= form_for @user do |f| %>
    <div class="form-group">
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </div>
    <div class="form-group">
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </div>
    <div class="form-group">
      <%= f.label :User_name %>
      <%= f.text_field :alias %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class="form-group">
      <%= f.label :phone %>
      <%= f.text_field :phone %>
    </div>
    <div class="form-group">
      <%= f.label :gender %>
      <%= f.text_field :gender %>
    </div>
    <div class="form-group">
      <%= f.label :height %>
      <%= f.text_field :height %>
    </div>
    <div class="form-group">
      <%= f.label :weight %>
      <%= f.text_field :weight %>
    </div>
    <div class="form-group">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
    <div class="form-group">
      <%= f.label :image %>
      <%= f.file_field :image %>
    </div>
  	<%= f.submit "Save Changes" %>
  <% end %>
</form>

app/views/users/index.html.erb
<ul>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.first_name %></td>
      <td><%= user.email %></td>
      <td><%= link_to 'Show', user %></td>
      <td><%= link_to 'Edit', user %></td>
      <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</ul>

app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->
<h1>Sign Up</h1>
<%= form_for @user do |f| %>
  <div>
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div>
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div>
    <%= f.label :User_name %>
    <%= f.text_field :alias %>
  </div>
  <div>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>
  <div>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/users/show.html.erb
<%= image_tag @user.image.url(:large) %>
<br>
<br>
<strong>First Name: </strong><%= @user.first_name %>
<br>
<br>
<strong>Last Name: </strong><%= @user.last_name %>
<br>
<br>
<strong>Username: </strong><%= @user.alias %>
<br>
<br>
<strong>Email: </strong><%= @user.email %>
<br>
<br>
<strong>Phone Number: </strong><%= @user.phone %>
<br>
<br>
<strong>Gender: </strong><%= @user.gender %>
<br>
<br>
<strong>Height (cm): </strong><%= @user.height %>
<br>
<br>
<strong>Weight (kg): </strong><%= @user.weight %>
<br>
<br>
<strong>Description: </strong><%= @user.description %>
<br>
<br>
<%= link_to 'Edit', edit_user_path, class:"btn btn-primary"  %>